### ISSUE TITLE
Publications DL

### ISSUE THREAD

**Issue by dlucanu** [EuroProofNet/europroofnet.github.io#108]
Here are some papers published in 2022-2023 that I co-authored and they are related to the action:

@article{DBLP:journals/jlap/ChenLR23,
  author       = {Xiaohong Chen and
                  Dorel Lucanu and
                  Grigore Rosu},
  title        = {Capturing constrained constructor patterns in matching logic},
  journal      = {J. Log. Algebraic Methods Program.},
  volume       = {130},
  pages        = {100810},
  year         = {2023},
  url          = {https://doi.org/10.1016/j.jlamp.2022.100810},
  doi          = {10.1016/j.jlamp.2022.100810},
  timestamp    = {Mon, 28 Aug 2023 21:32:06 +0200},
  biburl       = {https://dblp.org/rec/journals/jlap/ChenLR23.bib},
  bib source    = {dblp computer science bibliography, https://dblp.org}
}

@article{DBLP:journals/corr/abs-2309-13798,
  author       = {Dorel Lucanu},
  title        = {Matching-Logic-Based Understanding of Polynomial Functors and their
                  Initial/Final Models},
  journal      = {CoRR},
  volume       = {abs/2309.13798},
  year         = {2023},
  url          = {https://doi.org/10.48550/arXiv.2309.13798},
  doi          = {10.48550/arXiv.2309.13798},
  eprinttype    = {arXiv},
  eprint       = {2309.13798},
  timestamp    = {Wed, 27 Sep 2023 16:51:35 +0200},
  biburl       = {https://dblp.org/rec/journals/corr/abs-2309-13798.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}

@inproceedings{DBLP:conf/ictac/Alexandru-IoanL22,
  author       = {Lungu Alexandru{-}Ioan and
                  Dorel Lucanu},
  editor       = {Helmut Seidl and
                  Zhiming Liu and
                  Corina S. Pasareanu},
  title        = {A Matching Logic Foundation for Alk},
  booktitle    = {Theoretical Aspects of Computing - {ICTAC} 2022 - 19th International
                  Colloquium, Tbilisi, Georgia, September 27-29, 2022, Proceedings},
  series       = {Lecture Notes in Computer Science},
  volume       = {13572},
  pages        = {290--304},
  publisher    = {Springer},
  year         = {2022},
  url          = {https://doi.org/10.1007/978-3-031-17715-6\_19},
  doi          = {10.1007/978-3-031-17715-6\_19},
  timestamp    = {Fri, 07 Oct 2022 16:33:00 +0200},
  biburl       = {https://dblp.org/rec/conf/ictac/Alexandru-IoanL22.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}

@article{CIOBACA2023100894,
title = {Operationally-based program equivalence proofs using LCTRSs},
journal = {Journal of Logical and Algebraic Methods in Programming},
volume = {135},
pages = {100894},
year = {2023},
issn = {2352-2208},
doi = {https://doi.org/10.1016/j.jlamp.2023.100894},
url = {https://www.sciencedirect.com/science/article/pii/S2352220823000482},
author = {Ştefan Ciobâcă and Dorel Lucanu and Andrei Sebastian Buruiană}
}

@Inproceedings{EPTCS389.4,
  author    = {Lucanu, Dorel},
  year      = {2023},
  title     = {Matching-Logic-Based Understanding of Polynomial Functors and their Initial/Final Models},
  editor    = {Cheval, Hora\c{t}iu and Leu\c{s}tean, Lauren\c{t}iu and Sipo\c{s}, Andrei},
  booktitle = {{\rm Proceedings 7th Symposium on}
               Working Formal Methods,
               {\rm Bucharest, Romania, 21-22 September 2023}},
  series    = {Electronic Proceedings in Theoretical Computer Science},
  volume    = {389},
  publisher = {Open Publishing Association},
  pages     = {41-55},
  doi       = {10.4204/EPTCS.389.4},
}

@inproceedings{DBLP:journals/corr/abs-2110-11700,
  author       = {Andrei Arusoaie and
                  Dorel Lucanu},
  editor       = {Vlad Rusu},
  title        = {Proof-Carrying Parameters in Certified Symbolic Execution: The Case
                  Study of Antiunification},
  booktitle    = {Proceedings of the Sixth Working Formal Methods Symposium, {FROM}
                  2022, "Al. I. Cuza University", Iasi, Romania, 19-20 September, 2022},
  series       = {{EPTCS}},
  volume       = {369},
  pages        = {1--16},
  year         = {2022},
  url          = {https://doi.org/10.4204/EPTCS.369.1},
  doi          = {10.4204/EPTCS.369.1},
  timestamp    = {Mon, 28 Aug 2023 21:26:21 +0200},
  biburl       = {https://dblp.org/rec/journals/corr/abs-2110-11700.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}

**Comment by dtraytel** [comment]
Added, thanks Dorel.
