### ISSUE TITLE
Publications

### ISSUE THREAD

**Issue by tjark** [EuroProofNet/europroofnet.github.io#109]
Please feel free to add the following publication:

@inproceedings{DBLP:conf/frocos/TorstenssonW23,
  author       = {Olle Torstensson and
                  Tjark Weber},
  editor       = {Uli Sattler and
                  Martin Suda},
  title        = {Hammering Floating-Point Arithmetic},
  booktitle    = {Frontiers of Combining Systems - 14th International Symposium, FroCoS
                  2023, Prague, Czech Republic, September 20-22, 2023, Proceedings},
  series       = {Lecture Notes in Computer Science},
  volume       = {14279},
  pages        = {217--235},
  publisher    = {Springer},
  year         = {2023},
  url          = {https://doi.org/10.1007/978-3-031-43369-6\_12},
  doi          = {10.1007/978-3-031-43369-6\_12},
  timestamp    = {Sun, 24 Sep 2023 15:46:26 +0200},
  biburl       = {https://dblp.org/rec/conf/frocos/TorstenssonW23.bib},
  bibsource    = {dblp computer science bibliography, https://dblp.org}
}

**Comment by dtraytel** [comment]
Added, thanks Tjark.
