### ISSUE TITLE
Publications

### ISSUE THREAD

**Issue by logicosimo** [EuroProofNet/europroofnet.github.io#111]
Please feel free to add the following paper to EuroProofNet publication list:

@article{maggesi2023mechanising,
  title={Mechanising {G}{\"o}del--{L}{\"o}b {P}rovability {L}ogic in {HOL} {L}ight},
  author={Maggesi, Marco and Perini Brogi, Cosimo},
  journal={Journal of Automated Reasoning},
  volume={67},
  number={3},
  pages={29},
  year={2023},
  publisher={Springer}
}

**Comment by dtraytel** [comment]
Added, thanks Cosimo.
