### ISSUE TITLE
Suggested additions to website

### ISSUE THREAD

**Issue by bartbog** [EuroProofNet/europroofnet.github.io#216]
JOBS:

- July 31, 2024 (Deadline) Postdoc position in ERC CoG project "CertiFOX" on trustworthy combinatorial optimization using proof logging https://www.kuleuven.be/personeel/jobsite/jobs/60344086?utm_medium=jobsites&utm_source=academicpositions

Related project 
- CertiFOX: Certified First-Order Model Expansion  (ERC Consolidator Grant to Bart Bogaerts) https://www.bartbogaerts.eu/projects/certifox

**Comment by fblanqui** [comment]
added in https://github.com/EuroProofNet/europroofnet.github.io/commit/4c6688e42b795b9e22c4b584b2c23914215be9e7
