### ISSUE TITLE
Four Geometry Problems to Introduce Automated Deduction in Secondary Schools

### ISSUE THREAD

**Issue by GeoTiles** [EuroProofNet/europroofnet.github.io#22]
A paper in the ThEdu'21/EPTCS 354 - Automated Deduction in Secondary Schools

Quaresma, Pedro and Santos, Vanda Four Geometry Problems to Introduce Automated Deduction in Secondary Schools, Proceedings 10th International Workshop on Theorem Proving Components for Educational Software, EPTCS 354, pp. 27--42 2022. DOI: [10.4204/EPTCS.354.3](http://dx.doi.org/10.4204/EPTCS.354.3)

Pedro Quaresma, University of Coimbra

**Comment by dtraytel** [comment]
Thanks, Pedro. Added.
