### ISSUE TITLE
Pre-publication arising from STSM

### ISSUE THREAD

**Issue by andrejbauer** [EuroProofNet/europroofnet.github.io#221]
The pre-print https://arxiv.org/abs/2409.17664 is a direct consequence of the two STSM visits by Danel Ahman to Andrej Bauer in 2024. It has been submitted for publication (and it acknwoledges EuroProofNet). 

In addition, an early version of the work has been represented at TYPES 2024:

> Danel Ahman and Andrej Bauer: Comodule Representations of Second-Order Functionals, TYPES 2024

**Comment by fblanqui** [comment]
Thanks
