### ISSUE TITLE
Evolution of Automated Deduction and Dynamic Constructions in Geometry

### ISSUE THREAD

**Issue by GeoTiles** [EuroProofNet/europroofnet.github.io#23]
A chapter of a (Springer) book reviewing the area of automated deduction and dynamic construction in geometry.

Quaresma, Pedro, Evolution of Automated Deduction and Dynamic Constructions in Geometry, in Mathematics education in the age of Artificial intelligence, chp. 1, pp. 3--22, Mathematics Education in the Digital Era, Springer, 2022. DOI: [10.1007/978-3-030-86909-0](http://dx.doi.org/10.1007/978-3-030-86909-0)

Pedro Quaresma, University of Coimbra

**Comment by dtraytel** [comment]
Thanks, Pedro. Added.
