### ISSUE TITLE
TGTP, Thousand of Geometric problems for geometric Theorem Provers 

### ISSUE THREAD

**Issue by GeoTiles** [EuroProofNet/europroofnet.github.io#24]
A problems database for Geometry 

TGTP, Thousand of Geometric problems for geometric Theorem Provers 

http://hilbert.mat.uc.pt/TGTP/index.php

Pedro Quaresma, University of Coimbra

**Comment by dtraytel** [comment]
Thanks, Pedro. This is not really a paper publication, so I added it under tools (in the new category "Problem data bases") along with TPTP.
