### ISSUE TITLE
To include in the scientific report

### ISSUE THREAD

**Issue by mhermo** [EuroProofNet/europroofnet.github.io#96]
We have a conference paper and a journal paper to include in the scientific report. The references are these ones:

Montserrat Hermo, Paqui Lucio, César Sánchez: Tableaux for Realizability of Safety Specifications. Formal Methods 2023, pp: 495-513.

Alex Abuin, Alexander Bolotov, Montserrat Hermo, Paqui Lucio: Tableaux and sequent calculi for CTL and ECTL: Satisfiability test with certifying proofs and models. J. Log. Algebraic Methods Program. 130: 100828 (2023).

Montserrat Hermo

**Comment by fblanqui** [comment]
Thank you. Could you please provide URLs (doi)?

**Comment by fblanqui** [comment]
done

**Comment by mhermo** [comment]
Sorry, 
the first paper: https://doi.org/10.1007/978-3-031-27481-7_28
The second paper: https://doi.org/10.1016/j.jlamp.2022.100828
